name = "ecoguesser"
compatibility_date = "2024-09-23"
#pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "ecoguesser"
database_id = "9d72c0a5-30f0-48b9-ab93-b914194e49a6"