// scripts/buildStateAdjacency.js
// One-time generator for src/data/stateAdjacency.js -- a state name -> list
// of bordering state names lookup, used by BlitzCard.jsx's "close call"
// wrong-guess feedback (a miss that's still right next door to the correct
// state(s) gets a softer badge instead of a flat "Wrong").
//
// Deliberately does NOT add a polygon-adjacency library (turf etc.) -- the
// TopoJSON format already stores this for free: adjacent polygons share
// literal arc indices in their `arcs` field (that's the whole point of the
// topology -- one boundary line, referenced by both neighbors, instead of
// two separately-duplicated ones). So "does state A border state B" reduces
// to "do their arc-index sets intersect", computed once here from
// public/india-states.topojson and written out as a plain lookup object --
// same approach scripts/convertStatesTopo.js already uses (plain Node +
// fs, no extra packages). Not even require('topojson-client') is needed
// here, just raw JSON.
//
// Run manually after india-states.topojson changes: `node scripts/buildStateAdjacency.js`

const fs = require('fs');
const path = require('path');

const TOPO_PATH = path.join(__dirname, '..', 'public', 'india-states.topojson');
const OUT_PATH = path.join(__dirname, '..', 'src', 'data', 'stateAdjacency.js');

const topo = JSON.parse(fs.readFileSync(TOPO_PATH, 'utf8'));
const geometries = topo.objects['india-states'].geometries;

// TopoJSON arc indices are negative when a ring traverses an arc in reverse
// (bitwise-complemented per the spec: ~i, not -i) -- canon() maps both
// directions of the same physical arc to one non-negative id so sharing is
// detected regardless of which state "wrote" it forward vs reversed.
function canon(i) {
  return i < 0 ? ~i : i;
}

// Polygon.arcs is an array of rings (each a plain array of arc indices);
// MultiPolygon.arcs is an array of Polygons' arcs, one level deeper. Flat
// recursion by declared nesting depth rather than a generic deep-flatten,
// so an unexpected shape fails loudly (TypeError) instead of silently
// mis-reading arcs.
function flatten(field, depth) {
  if (depth === 0) return field.slice();
  return field.flatMap((sub) => flatten(sub, depth - 1));
}

function arcIndicesOf(geometry) {
  if (geometry.type === 'Polygon') return flatten(geometry.arcs, 1);
  if (geometry.type === 'MultiPolygon') return flatten(geometry.arcs, 2);
  return [];
}

const arcSetByState = new Map(); // st_nm -> Set<canonical arc index>
for (const g of geometries) {
  const name = g.properties.st_nm;
  arcSetByState.set(name, new Set(arcIndicesOf(g).map(canon)));
}

const names = [...arcSetByState.keys()];
const adjacency = {};
for (const name of names) adjacency[name] = [];

for (let i = 0; i < names.length; i++) {
  for (let j = i + 1; j < names.length; j++) {
    const a = names[i];
    const b = names[j];
    let shares = false;
    for (const arc of arcSetByState.get(a)) {
      if (arcSetByState.get(b).has(arc)) { shares = true; break; }
    }
    if (shares) {
      adjacency[a].push(b);
      adjacency[b].push(a);
    }
  }
}

for (const name of names) adjacency[name].sort();

const header = `// src/data/stateAdjacency.js
// GENERATED by scripts/buildStateAdjacency.js -- do not hand-edit.
// State name (matches india-states.topojson's st_nm / config's site.state
// values) -> array of directly bordering state names, derived from shared
// TopoJSON arcs (see the build script for how "shared arc" = "shared
// border" is computed). Island states (Andaman & Nicobar, Lakshadweep)
// correctly resolve to an empty array -- they share no land arc with
// anything. Consumed by BlitzCard.jsx to detect a "close call" wrong guess.

export const STATE_ADJACENCY = `;

fs.writeFileSync(OUT_PATH, header + JSON.stringify(adjacency, null, 2) + ';\n');
console.log(`Wrote ${OUT_PATH} (${names.length} states)`);
